language: objective-c
osx_image: xcode8.2
env:
  global:
  - FRAMEWORK_NAME=GIGPassbook
before_script:
  - carthage version
  - carthage bootstrap --platform iOS
script:
  - set -o pipefail && xcodebuild -project GIGPassbook.xcodeproj -scheme GIGPassbook -sdk iphonesimulator -destination "platform=iOS Simulator,OS=10.1,name=iPhone 6" test | xcpretty
before_deploy:
  - carthage build --no-skip-current
  - carthage archive $FRAMEWORK_NAME
deploy:
  provider: releases
  api_key:
    secure: pbVeWdl36HV4lyRBDBcawegP+gVIajhuLL17JtOhJig9QDFs0/0aGAZxoIGa7erqyiLPVTi8XADIOJhMv5YBeRBP56PJM944GzCRyf9Uh3qoNzRQ3db0FPrQuAfgqf+J/XRlZg7p/oasjnZJG6fPh+tO/i/rtonO50AOWVlMfnspqRKJEPcUvW0TeBEdhbKhQzARbDXi4BgcnmY53ZzY4zGv3ktPpFQHA7k0O/7VPPnERHqgslPerjS/jUhdEjkK4faU6bFTNodynKswdRkC0QGNJA7F6MiGmqXbm3f11fDIgLvf8IF5gheS/GKivmpao1yTGrkJVLRzUzV5i5mL59P/vdnNxd8aLIcXHQUOI11LXONK3FaaQcSG/T/ukryQe8T9XifiBKUoM+9wiUP5wPp6tvcjCNoJ0YqZIf+mh8BsN17BQu6BbUC/o1ckH+C1QSQYp1SE5SZVkF1jTFQpPPZ8/Lst32bkdgh9mPWxYjo8qjAK/y7gOYE/T3850j7TyCfH4Y/bgZaPLLq+HDZFwvChsQdxEdjY/6xpYpE4WyON/cfSKygbfiOo1Z46Ov5OHx6M68WYp3C/vTvNCHjC9mK8kGfg+Jf9vlZrqPrbmOvDonczeJY5KKput/FDK3VxKRlOE1Ffnfe6xvs58YqDAzY6q40PFAfBV1P1GCYC3n4=
  file: "$FRAMEWORK_NAME.framework.zip"
  skip_cleanup: true
  on:
    repo: gigigoapps/gigigo-ios-passbook
    tags: true
notifications:
  slack:
    secure: BKMXm4fFvw+KV6QyojkH2iH3XIwF8koQxjOOVCbCfu7hB9zt3cDhh2wgbj/PWbvXTm79BAZ+1Cw5VPScgRxCwaqbGfKQTLMh8NylEh7PwaC6GxyOUjt7v9uit7OcnQQSTQOhvkqZAGkDttZ8I/Wa/IqsLYmqSW4CYsB+DcR5BBWBUnDeAym4FvMEGXfDoCI870fxqa+Jh7podpx+Zxuy5DOXEJ16oixbOmlZcHE9uLg2XJ2KGSN1JqkJ0MJNIPMXr2WjLTxQ6aGuNjp9DXkyT8gVwnU6DcqPg1DbJDPPXnVbd1DM++9bk0Wp93Q9kRGxCqL/N+B8qyBkIcIHhEmWL/lm0pX4pqoU/jNbTrL03OT8eu5uR8rvpexiQ13LLSQhq2DL49vCzM7OA8gt+lh+2MJYeEkeLlYRyrheNF1kVkWoHofar62G/J/u/1fAFT8EdFJx3tINoLAhBQkb59qCySttIfpPp1YeRIyWBiXlCPU4zw/j84U3l81pHElpCFWXOBO5pwvBLhO1bRuOFumbtCE5fXDXaj69Ed51SlkFxmeD6lqjJ0yhPH9O0U+eFvnQEtIrK1ArLiOpLOlvXXRqA8ISFWRoZW47gQV59YWx4WyBJzK6JyVzb/xsBHzvY+0vR9oM0morewoWg4hcYH1yOiMnGeLOyslbQX1bxvEf8wI=
